import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { drills, findDrill } from "../data/drills";
import { SessionDraft } from "../types";

type Props = { ageGroup: string; draft: SessionDraft; hasLoadedDraft: boolean; setDraft: React.Dispatch<React.SetStateAction<SessionDraft>> };

export function SessionBuilderScreen({ ageGroup, draft, hasLoadedDraft, setDraft }: Props) {
  const total = draft.blocks.reduce((sum, block) => sum + block.minutes, 0);
  const changeMinutes = (id: string, amount: number) => setDraft((current) => ({ ...current, blocks: current.blocks.map((block) => block.id === id ? { ...block, minutes: Math.max(5, block.minutes + amount) } : block) }));
  const addDrill = (drillId: string) => { const drill = findDrill(drillId); setDraft((current) => ({ ...current, blocks: [...current.blocks, { id: `block-${Date.now()}`, drillId, minutes: drill.defaultMinutes }] })); };
  return <View style={styles.container}><View style={styles.sessionCard}><Text style={styles.cardLabel}>Session plan</Text><TextInput accessibilityLabel="Session title" onChangeText={(title) => setDraft((current) => ({ ...current, title }))} placeholder="Session title" placeholderTextColor="#778173" style={styles.titleInput} value={draft.title} /><View style={styles.meta}><Text style={styles.metaText}>{ageGroup} guidance selected</Text><Text style={styles.metaText}>{total} min total</Text></View></View><View style={styles.section}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Your session flow</Text><Text style={styles.saved}>{hasLoadedDraft ? "Saved locally" : "Loading..."}</Text></View><View style={styles.blockList}>{draft.blocks.map((block, index) => { const drill = findDrill(block.drillId); return <View key={block.id} style={styles.block}><View style={styles.number}><Text style={styles.numberText}>{index + 1}</Text></View><View style={styles.blockCopy}><Text style={styles.category}>{drill.category}</Text><Text style={styles.blockTitle}>{drill.title}</Text><Text style={styles.description}>{drill.description}</Text></View><View style={styles.actions}><View style={styles.timeControls}><Pressable onPress={() => changeMinutes(block.id, -5)} style={styles.timeButton}><Text style={styles.timeButtonText}>-</Text></Pressable><Text style={styles.time}>{block.minutes}m</Text><Pressable onPress={() => changeMinutes(block.id, 5)} style={styles.timeButton}><Text style={styles.timeButtonText}>+</Text></Pressable></View><Pressable onPress={() => setDraft((current) => ({ ...current, blocks: current.blocks.filter((item) => item.id !== block.id) }))}><Text style={styles.remove}>Remove</Text></Pressable></View></View>; })}</View></View><View style={styles.section}><Text style={styles.sectionTitle}>Drill library</Text><Text style={styles.hint}>Quick, adaptable games to shape into your own session.</Text><View style={styles.library}>{drills.map((drill) => <View key={drill.id} style={styles.drillCard}><View style={styles.drillTop}><Text style={styles.category}>{drill.category}</Text><Text style={styles.drillTime}>{drill.defaultMinutes} min</Text></View><Text style={styles.drillTitle}>{drill.title}</Text><Text style={styles.description}>{drill.description}</Text><Text style={styles.equipment}>{drill.equipment}</Text><Pressable onPress={() => addDrill(drill.id)} style={styles.addButton}><Text style={styles.addButtonText}>Add to session</Text></Pressable></View>)}</View></View></View>;
}

const styles = StyleSheet.create({
  actions: { alignItems: "flex-end", gap: 8 }, addButton: { alignItems: "center", backgroundColor: "#dce8b1", borderRadius: 11, marginTop: 10, paddingVertical: 9 }, addButtonText: { color: "#18321f", fontSize: 13, fontWeight: "800" }, block: { backgroundColor: "#f8f5ed", borderColor: "#ded7c8", borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 10, padding: 13 }, blockCopy: { flex: 1, gap: 3 }, blockList: { gap: 8 }, blockTitle: { color: "#1a2a1e", fontSize: 16, fontWeight: "800" }, cardLabel: { color: "#dce8b1", fontSize: 11, fontWeight: "800", letterSpacing: 1.5, textTransform: "uppercase" }, category: { color: "#6b7667", fontSize: 10, fontWeight: "800", letterSpacing: 1, textTransform: "uppercase" }, container: { gap: 22 }, description: { color: "#657063", fontSize: 12, lineHeight: 17 }, drillCard: { backgroundColor: "#f8f5ed", borderColor: "#ded7c8", borderRadius: 18, borderWidth: 1, padding: 14 }, drillTime: { color: "#526051", fontSize: 12, fontWeight: "800" }, drillTitle: { color: "#1a2a1e", fontSize: 17, fontWeight: "800", marginTop: 5 }, drillTop: { flexDirection: "row", justifyContent: "space-between" }, equipment: { color: "#6c7567", fontSize: 11, fontStyle: "italic", marginTop: 8 }, hint: { color: "#626d60", fontSize: 14, lineHeight: 20 }, library: { gap: 10 }, meta: { borderTopColor: "#46604d", borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", paddingTop: 10 }, metaText: { color: "#d6e1d2", fontSize: 12 }, number: { alignItems: "center", backgroundColor: "#e7edcf", borderRadius: 12, height: 25, justifyContent: "center", width: 25 }, numberText: { color: "#18321f", fontSize: 12, fontWeight: "800" }, remove: { color: "#9a6656", fontSize: 11, fontWeight: "800" }, saved: { color: "#687464", fontSize: 11, fontWeight: "700" }, section: { gap: 10 }, sectionHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, sectionTitle: { color: "#1a2a1e", fontSize: 19, fontWeight: "800", letterSpacing: -0.2 }, sessionCard: { backgroundColor: "#1c3825", borderRadius: 24, gap: 10, padding: 20 }, time: { color: "#1a2a1e", fontSize: 13, fontWeight: "800", minWidth: 29, textAlign: "center" }, timeButton: { alignItems: "center", backgroundColor: "#e7edcf", borderRadius: 9, height: 26, justifyContent: "center", width: 26 }, timeButtonText: { color: "#18321f", fontSize: 16, fontWeight: "800", lineHeight: 18 }, timeControls: { alignItems: "center", flexDirection: "row", gap: 5 }, titleInput: { color: "#ffffff", fontSize: 27, fontWeight: "800", letterSpacing: -0.6, padding: 0 }
});
