import { Modal, Pressable, StyleSheet, Text, View } from "react-native";

export function MenuDrawer({ onClose, onOpenSquad, visible }: { onClose: () => void; onOpenSquad: () => void; visible: boolean }) {
  return <Modal animationType="fade" onRequestClose={onClose} transparent visible={visible}><View style={styles.overlay}><Pressable accessibilityLabel="Close menu" onPress={onClose} style={styles.backdrop} /><View style={styles.drawer}><View style={styles.header}><Text style={styles.title}>Menu</Text><Pressable accessibilityLabel="Close menu" onPress={onClose} style={styles.close}><Text style={styles.closeText}>x</Text></Pressable></View><Pressable onPress={onOpenSquad} style={styles.item}><View style={styles.icon}><Text style={styles.iconText}>S</Text></View><View><Text style={styles.itemTitle}>Squad</Text><Text style={styles.itemHint}>Names and match-day availability</Text></View><Text style={styles.chevron}>›</Text></Pressable></View></View></Modal>;
}

const styles = StyleSheet.create({
  backdrop: StyleSheet.absoluteFillObject, chevron: { color: "#6f786c", fontSize: 25, marginLeft: "auto" }, close: { alignItems: "center", backgroundColor: "#dce8b1", borderRadius: 10, height: 36, justifyContent: "center", width: 36 }, closeText: { color: "#18321f", fontSize: 19, fontWeight: "700" }, drawer: { backgroundColor: "#f4f0e6", borderBottomRightRadius: 22, borderTopRightRadius: 22, gap: 24, minHeight: "100%", padding: 24, paddingTop: 58, width: "84%" }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, icon: { alignItems: "center", backgroundColor: "#dce8b1", borderRadius: 10, height: 42, justifyContent: "center", width: 42 }, iconText: { color: "#18321f", fontSize: 17, fontWeight: "800" }, item: { alignItems: "center", backgroundColor: "#ffffff", borderColor: "#ded7c8", borderRadius: 12, borderWidth: 1, flexDirection: "row", gap: 12, padding: 14 }, itemHint: { color: "#6a7467", fontSize: 12, marginTop: 2 }, itemTitle: { color: "#1a2a1e", fontSize: 16, fontWeight: "800" }, overlay: { backgroundColor: "rgba(20, 40, 29, 0.32)", flex: 1 }, title: { color: "#14281d", fontFamily: "Avenir Next Condensed", fontSize: 30, fontWeight: "800", letterSpacing: -0.7 }
});
